### ISSUE TITLE
Include a analysis scheme

### ISSUE THREAD

**Issue by JavierDiezSierra** [IHCantabria/NEOPRENE#10]
Include a rainfall analysis scheme in the [documentation](https://github.com/IHCantabria/NEOPRENE/tree/main/doc) with the different validation functions.

**Comment by JavierDiezSierra** [comment]
@manueldeljesus, @navass11, take a look of this scheme. I think it would be more appropriated for the paper. 

It could still be customized more in deep to make it look more rigorous (change colors, reduce sizes, etc).



![Untitled drawing(3)](https://user-images.githubusercontent.com/32273213/152134299-9c2a6334-0d59-434c-bbcc-276173138cfa.png)

**Comment by manueldeljesus** [comment]
It looks really cool. Let me see how to include it in the paper and check if it would need some adaptation.
