### ISSUE TITLE
Change name of the analysis functions.

### ISSUE THREAD

**Issue by JavierDiezSierra** [IHCantabria/NEOPRENE#15]
Some of the functions defined in section 3.1.3 (Analysis) should be replaced in the manuscript and in the code:

- figure_correlation_fig() -> correlation_fig()
- figure_disaggregation_fig -> disaggregation_fig()

**Comment by navass11** [comment]
The names of the functions have already been changed. @manueldeljesus , it remains to be changed in the paper.
