### ISSUE TITLE
STNSRP model taking up huge RAM space and long computational time

### ISSUE THREAD

**Issue by sabahparvaze** [IHCantabria/NEOPRENE#21]
I used the STNSRP model for my basin, having 18 rainfall stations and an area of 2000 sq km. However, the model is taking over 24 hours to run for simulating 100 years' data. It is also occupying a lot of RAM (12 gb). How can I improve the computational time and memory requirement?

**Comment by JavierDiezSierra** [comment]
Are you using the latest release updated during July?

**Comment by sabahparvaze** [comment]
YESyes

**Comment by sabahparvaze** [comment]
Yes

**Comment by JavierDiezSierra** [comment]
The latest release includes some updates which improve the speed of the model. Did this help to solve your problem?

**Comment by sabahparvaze** [comment]
Thank you for replying.
I am working with the latest version available, but the problem is still
the same. Also, the spatial model critically underestimates the rainfall
amount.

**Comment by manueldeljesus** [comment]
May you please share your configuration files to check if the problem may come from there?

**Comment by sabahparvaze** [comment]
I am sending the files I am using. Please see the attachment.

**Comment by manueldeljesus** [comment]
You did not attach any files. You should go to the GitHub page and upload the files there, in the text area. There is some help around the page explaining how to upload files to the interface.

**Comment by sabahparvaze** [comment]
There was some problem previously. Please see attachment
[SNSRP.zip](https://github.com/IHCantabria/NEOPRENE/files/10145576/SNSRP.zip)

**Comment by sabahparvaze** [comment]
Thank you very much.
