### ISSUE TITLE
Include aggregated mathematical equations

### ISSUE THREAD

**Issue by manueldeljesus** [IHCantabria/NEOPRENE#5]
We should include the aggregated equations for the parameters somewhere in the doc folder of the repo. The ideal would be to reference the original equation number in the paper we took it from, and show the equations in LaTeX for easy use of the readers and library users.

**Comment by JavierDiezSierra** [comment]
I included a jupyter notebook where the aggregated statistics for the NSRPM and the STNSRPM are described [Statistical_properties.ipynb](https://github.com/IHCantabria/NEOPRENE/blob/main/doc/Statistical_properties.ipynb). Papers and equations used are also referenced.
